//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // класс с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить элемент, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте проект Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, используемый этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Переопределяет свойство CurrentUICulture текущего потока для всех
        ///   подстановки ресурсов с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Добавить в корзину.
        /// </summary>
        internal static string addToCart {
            get {
                return ResourceManager.GetString("addToCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Adobe.
        /// </summary>
        internal static string adobe {
            get {
                return ResourceManager.GetString("adobe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Адресс.
        /// </summary>
        internal static string adress {
            get {
                return ResourceManager.GetString("adress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Киев, Серпова, 11.
        /// </summary>
        internal static string adressActual {
            get {
                return ResourceManager.GetString("adressActual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Все категории.
        /// </summary>
        internal static string allCategories {
            get {
                return ResourceManager.GetString("allCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Бесплатная доставка на все заказы.
        /// </summary>
        internal static string allDeleviry {
            get {
                return ResourceManager.GetString("allDeleviry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как and.
        /// </summary>
        internal static string and {
            get {
                return ResourceManager.GetString("and", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Atlassian.
        /// </summary>
        internal static string atlassian {
            get {
                return ResourceManager.GetString("atlassian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Avast.
        /// </summary>
        internal static string avast {
            get {
                return ResourceManager.GetString("avast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Назад к покупкам.
        /// </summary>
        internal static string backToShopping {
            get {
                return ResourceManager.GetString("backToShopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Войдя в систему, вы соглашаетесь с нашими.
        /// </summary>
        internal static string Bylogginginyouagreetoour {
            get {
                return ResourceManager.GetString("Bylogginginyouagreetoour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Категории.
        /// </summary>
        internal static string categories {
            get {
                return ResourceManager.GetString("categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Коментарий.
        /// </summary>
        internal static string comment {
            get {
                return ResourceManager.GetString("comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Контактная информация.
        /// </summary>
        internal static string contactInfo {
            get {
                return ResourceManager.GetString("contactInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Оформить заказ.
        /// </summary>
        internal static string createPayment {
            get {
                return ResourceManager.GetString("createPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как СУБД.
        /// </summary>
        internal static string DBMS {
            get {
                return ResourceManager.GetString("DBMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Бесплатная и быстрая доставка.
        /// </summary>
        internal static string deleviry {
            get {
                return ResourceManager.GetString("deleviry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Программного обеспечения ведущих производителей по справедливым и гибким ценам для домашнего пользователя для крупных предприятий..
        /// </summary>
        internal static string description {
            get {
                return ResourceManager.GetString("description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Описание.
        /// </summary>
        internal static string descriptionAct {
            get {
                return ResourceManager.GetString("descriptionAct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Email.
        /// </summary>
        internal static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как sun30point@gmail.com.
        /// </summary>
        internal static string emailActual {
            get {
                return ResourceManager.GetString("emailActual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Пустая корзина.
        /// </summary>
        internal static string emptyCart {
            get {
                return ResourceManager.GetString("emptyCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Инжернерное ПО.
        /// </summary>
        internal static string engineering {
            get {
                return ResourceManager.GetString("engineering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Esset.
        /// </summary>
        internal static string esset {
            get {
                return ResourceManager.GetString("esset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Фамилия.
        /// </summary>
        internal static string firstName {
            get {
                return ResourceManager.GetString("firstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Забыли пароль!.
        /// </summary>
        internal static string forgotPassword {
            get {
                return ResourceManager.GetString("forgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Домашняя.
        /// </summary>
        internal static string home {
            get {
                return ResourceManager.GetString("home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Информация.
        /// </summary>
        internal static string information {
            get {
                return ResourceManager.GetString("information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как элементов.
        /// </summary>
        internal static string items {
            get {
                return ResourceManager.GetString("items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как JetBrains.
        /// </summary>
        internal static string jetbrains {
            get {
                return ResourceManager.GetString("jetbrains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Вход.
        /// </summary>
        internal static string login {
            get {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как McAffee.
        /// </summary>
        internal static string mcaffee {
            get {
                return ResourceManager.GetString("mcaffee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Microsoft.
        /// </summary>
        internal static string microsoft {
            get {
                return ResourceManager.GetString("microsoft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как .
        /// </summary>
        internal static string myShopBag {
            get {
                return ResourceManager.GetString("myShopBag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Моя корзина.
        /// </summary>
        internal static string myShopingBag {
            get {
                return ResourceManager.GetString("myShopingBag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Имя.
        /// </summary>
        internal static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Новый.
        /// </summary>
        internal static string neW {
            get {
                return ResourceManager.GetString("neW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Офисные системы.
        /// </summary>
        internal static string officeSystems {
            get {
                return ResourceManager.GetString("officeSystems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Операционные системы.
        /// </summary>
        internal static string os {
            get {
                return ResourceManager.GetString("os", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Пароль.
        /// </summary>
        internal static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Телефон.
        /// </summary>
        internal static string phone {
            get {
                return ResourceManager.GetString("phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как +380677617676.
        /// </summary>
        internal static string phoneActual {
            get {
                return ResourceManager.GetString("phoneActual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Цена.
        /// </summary>
        internal static string price {
            get {
                return ResourceManager.GetString("price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как политика конфиденциальности.
        /// </summary>
        internal static string privacyPolicy {
            get {
                return ResourceManager.GetString("privacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Продукт.
        /// </summary>
        internal static string product {
            get {
                return ResourceManager.GetString("product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Описание продукта.
        /// </summary>
        internal static string productDescription {
            get {
                return ResourceManager.GetString("productDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Имя продукта.
        /// </summary>
        internal static string productName {
            get {
                return ResourceManager.GetString("productName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Системы програмирования.
        /// </summary>
        internal static string programmingSystems {
            get {
                return ResourceManager.GetString("programmingSystems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Количество.
        /// </summary>
        internal static string quantity {
            get {
                return ResourceManager.GetString("quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Быстрый просмотр.
        /// </summary>
        internal static string quickView {
            get {
                return ResourceManager.GetString("quickView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Зарегистрировать сейчас..
        /// </summary>
        internal static string registerNow {
            get {
                return ResourceManager.GetString("registerNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Напомнить мне!.
        /// </summary>
        internal static string rememberMe {
            get {
                return ResourceManager.GetString("rememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Удалить.
        /// </summary>
        internal static string remove {
            get {
                return ResourceManager.GetString("remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Перезаписать пароль.
        /// </summary>
        internal static string reTypePassword {
            get {
                return ResourceManager.GetString("reTypePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Поиск.
        /// </summary>
        internal static string search {
            get {
                return ResourceManager.GetString("search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Подпишитесь бесплатно.
        /// </summary>
        internal static string seengUpFree {
            get {
                return ResourceManager.GetString("seengUpFree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Сервисные системы.
        /// </summary>
        internal static string serviceSystems {
            get {
                return ResourceManager.GetString("serviceSystems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Корзина покупок.
        /// </summary>
        internal static string shoppingBasket {
            get {
                return ResourceManager.GetString("shoppingBasket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Войти!.
        /// </summary>
        internal static string SIGNIN {
            get {
                return ResourceManager.GetString("SIGNIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Войдите в свою учетную запись.
        /// </summary>
        internal static string signInYourAccount {
            get {
                return ResourceManager.GetString("signInYourAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как SketchUp.
        /// </summary>
        internal static string sketchUp {
            get {
                return ResourceManager.GetString("sketchUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Подкатегории.
        /// </summary>
        internal static string subCategories {
            get {
                return ResourceManager.GetString("subCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Подписаться.
        /// </summary>
        internal static string submit {
            get {
                return ResourceManager.GetString("submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Рассылка.
        /// </summary>
        internal static string subscription {
            get {
                return ResourceManager.GetString("subscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Спасибо ваш заказ, ваш заказ успешно отправлен! Ожидайте звонка менеджера!.
        /// </summary>
        internal static string successSend {
            get {
                return ResourceManager.GetString("successSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Условия и положения.
        /// </summary>
        internal static string TermsAndConditions {
            get {
                return ResourceManager.GetString("TermsAndConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Текстовые редакторы.
        /// </summary>
        internal static string textEditors {
            get {
                return ResourceManager.GetString("textEditors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как SunPoint Software.
        /// </summary>
        internal static string title {
            get {
                return ResourceManager.GetString("title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Вендеры.
        /// </summary>
        internal static string venders {
            get {
                return ResourceManager.GetString("venders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как ZWSoft.
        /// </summary>
        internal static string zwsoft {
            get {
                return ResourceManager.GetString("zwsoft", resourceCulture);
            }
        }
    }
}
