//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SunSoft.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prices
    {
        public int Id { get; set; }
        public string NameRu { get; set; }
        public string NameUk { get; set; }
        public string NameEn { get; set; }
        public string NameEs { get; set; }
        public string DescriptionRu { get; set; }
        public string DescriptionUk { get; set; }
        public string DescriptionEn { get; set; }
        public string DescriptionEs { get; set; }
        public string FrontImgUrl { get; set; }
        public string BackImgUrl { get; set; }
        public string Img1 { get; set; }
        public string Img2 { get; set; }
        public string Img3 { get; set; }
        public string Img4 { get; set; }
        public string ImgCart { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<double> PriceOld { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public Nullable<int> CurrencyUnitID { get; set; }
        public Nullable<int> VenderID { get; set; }
        public Nullable<bool> IsNew { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual Categories Categories { get; set; }
        public virtual CurrencyUnits CurrencyUnits { get; set; }
        public virtual Venders Venders { get; set; }
    }
}
